version: 2.1

jobs:
  test:
    docker:
    - image: docker
    steps:
    - setup_remote_docker
    - checkout
    - run: docker build -t test -f Dockerfile .
    # - run: go get ./... && go test ./...

workflows:
  main:
    jobs:
    - test
