version: 2.1

commands:
  docker-deploy:
    description: "TODO"
    parameters:
      tag:
        type: string
    steps:
    - setup_remote_docker
    - run: docker build -t celestialorb/solskin:<< parameters.tag >> -f Dockerfile .
    - run: docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
    - run: docker push celestialorb/solskin:<< parameters.tag >>

jobs:
  test:
    docker:
    - image: circleci/golang
    working_directory: /go/src/github.com/celestialorb/solskin
    steps:
    - checkout
    - run: go get -u github.com/golang/dep/cmd/dep
    - run: dep ensure -v
    - run: go test ./...
  
  build:
    docker:
    - image: docker
    steps:
    - checkout
    - docker-deploy:
        tag: latest
  
  deploy:
    docker:
    - image: docker
    steps:
    - checkout
    - docker-deploy:
        tag: ${CIRCLE_TAG}

workflows:
  version: 2

  main:
    jobs:
    - test
    - build:
        context: celestialorb
        requires:
          - test
        filters:
          branches:
            only: master
    - deploy:
        context: celestialorb
        requires:
          - test
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^\d+\.\d+\.\d+$/
