version: 2.1

jobs:
  test:
    docker:
    - image: theyorkshiredev/golang-git
    environment:
      GOPATH: /root/project
    steps:
    - checkout
    - run: mkdir -p ${GOPATH}
    - run: go get ./...
    - run: go test ./...

workflows:
  main:
    jobs:
    - test
