version: 2.1

jobs:
  test:
    docker:
    - image: circleci/golang
    working_directory: /go/src/github.com/celestialorb/solskin
    steps:
    # - setup_remote_docker
    - checkout
    - run: go get -v -t ./...
    - run: go test ./...

workflows:
  main:
    jobs:
    - test
