version: 2.1

jobs:
  test:
    docker:
    - image: circleci/golang
    working_directory: /go/src/github.com/celestialorb/solskin
    steps:
    - checkout
    - run: go get -u github.com/golang/dep/cmd/dep
    - run: dep ensure -v
    - run: go test ./...
  
  build:
    docker:
    - image: docker
    steps:
    - setup_remote_docker
    - checkout
    - run: docker build -t celestialorb/solskin -f Dockerfile .
    - run: docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
    - run: docker push celestialorb/solskin

workflows:
  version: 2

  main:
    jobs:
    - test
    - build:
        context: celestialorb
        requires:
          - test
        filters:
          branches:
            only: master
