version: 2.1

jobs:
  test:
    docker:
    - image: circleci/golang
    working_directory: /go/src/github.com/celestialorb/solskin
    steps:
    - checkout
    - run: echo ${GOPATH}
    - run: pwd
    - run: go get ./...
    - run: go test ./...

workflows:
  main:
    jobs:
    - test
